server:
  port: 10030
spring:
  application:
    name: ml-toolkit-service
  profiles:
    include: develop
  mvc:
    view:
      prefix: /WEB-INF/content/
      suffix: .jsp
  datasource:
    hikari:
      max-lifetime: 30000 # 控制池中连接的最长生命周期 默认值：1800000（30 分钟）


#  配置xml 所在的路径
mybatis-plus:
  mapper-locations: classpath*:com/ml/toolkit/**/dao/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ml: info
