spring:
  datasource:
    url: jdbc:mysql://47.100.4.229:3306/toolkit_develop?allowMultiQueries=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: Hanxide123..

# jwt 配置
jwt:
  secret: JWTSecret # 自定义密钥
  expiration: 28800000 # 过期时间 毫秒 8个小时
  tokenHead: Bearer #jwt规范， 客户端token开头需要加的一个字符串
  tokenHeader: Authorization # TokenKey,告诉客户端请求里加什么参数
  issuer: ml # 签发者